# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activestorage/all/activestorage.rbi
#
# activestorage-7.0.4

module ActiveStorage
  extend ActiveSupport::Autoload
end
module ActiveStorage::VERSION
end
class ActiveStorage::Error < StandardError
end
class ActiveStorage::InvariableError < ActiveStorage::Error
end
class ActiveStorage::UnpreviewableError < ActiveStorage::Error
end
class ActiveStorage::UnrepresentableError < ActiveStorage::Error
end
class ActiveStorage::IntegrityError < ActiveStorage::Error
end
class ActiveStorage::FileNotFoundError < ActiveStorage::Error
end
class ActiveStorage::PreviewError < ActiveStorage::Error
end
module ActiveStorage::Transformers
  extend ActiveSupport::Autoload
end
class ActiveStorage::Previewer
end
class ActiveStorage::Previewer::PopplerPDFPreviewer < ActiveStorage::Previewer
end
class ActiveStorage::Previewer::MuPDFPreviewer < ActiveStorage::Previewer
end
class ActiveStorage::Previewer::VideoPreviewer < ActiveStorage::Previewer
end
class ActiveStorage::Analyzer
end
class ActiveStorage::Analyzer::ImageAnalyzer < ActiveStorage::Analyzer
end
class ActiveStorage::Analyzer::ImageAnalyzer::ImageMagick < ActiveStorage::Analyzer::ImageAnalyzer
end
class ActiveStorage::Analyzer::ImageAnalyzer::Vips < ActiveStorage::Analyzer::ImageAnalyzer
end
class ActiveStorage::Analyzer::VideoAnalyzer < ActiveStorage::Analyzer
end
class ActiveStorage::Analyzer::AudioAnalyzer < ActiveStorage::Analyzer
end
class ActiveStorage::LogSubscriber < ActiveSupport::LogSubscriber
end
class ActiveStorage::Downloader
end
class ActiveStorage::Service
  extend ActiveSupport::Autoload
end
class ActiveStorage::Service::Registry
end
module ActiveStorage::Reflection
end
class ActiveStorage::Reflection::HasAttachedReflection < ActiveRecord::Reflection::MacroReflection
end
class ActiveStorage::Reflection::HasOneAttachedReflection < ActiveStorage::Reflection::HasAttachedReflection
end
class ActiveStorage::Reflection::HasManyAttachedReflection < ActiveStorage::Reflection::HasAttachedReflection
end
module ActiveStorage::Reflection::ReflectionExtension
end
module ActiveStorage::Reflection::ActiveRecordExtensions
  extend ActiveSupport::Concern
end
module ActiveStorage::Reflection::ActiveRecordExtensions::ClassMethods
end
class ActiveStorage::Engine < Rails::Engine
end
module ActiveStorage::Attached::Model
  extend ActiveSupport::Concern
end
module ActiveStorage::Attached::Model::ClassMethods
end
class ActiveStorage::Attached::One < ActiveStorage::Attached
end
class ActiveStorage::Attached::Many < ActiveStorage::Attached
end
module ActiveStorage::Attached::Changes
  extend ActiveSupport::Autoload
end
class ActiveStorage::Attached
end
class ActiveStorage::Attached::Changes::CreateOne
end
class ActiveStorage::Attached::Changes::CreateMany
end
class ActiveStorage::Attached::Changes::CreateOneOfMany < ActiveStorage::Attached::Changes::CreateOne
end
class ActiveStorage::Attached::Changes::DeleteOne
end
class ActiveStorage::Attached::Changes::DeleteMany
end
class ActiveStorage::Service::Configurator
end
class ActiveStorage::Transformers::Transformer
end
