# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/graphiql-rails/all/graphiql-rails.rbi
#
# graphiql-rails-1.8.0

module GraphiQL
end
module GraphiQL::Rails
end
class GraphiQL::Rails::Config
end
class GraphiQL::Rails::Engine < Rails::Engine
end
class GraphiQL::Rails::EditorsController < ActionController::Base
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_34
end
module GraphiQL::Rails::EditorsController::HelperMethods
  include ActionController::Base::HelperMethods
end
